apps/blog/urls.py
from django.urls import path
from . import views
from .views import ArticuloView, ArticuloDetailView, ArticuloListAPIView

app_name = 'blog'

urlpatterns = [
    path("blog", ArticuloView.as_view(), name="lista-articulos"),
    path("detail/<slug:slug>/", ArticuloDetailView.as_view(), name="detalle-articulo"),
    path('test-404/', views.trigger_404),
    path('api/articulos/', ArticuloListAPIView.as_view(), name='articulo-list'),

]

cyberblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('blog/', include('apps.blog.urls')),
    path('landing/', TemplateView.as_view(template_name='base/base.html'), name='landing'),  # Página de inicio
    path('users/', include('apps.users.urls')),
    path('', include('apps.home.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
from django.utils.text import slugify


class Articulo(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=200, unique=True)
    descripcion = models.CharField(max_length=255)
    image = models.FileField(upload_to="img", storage=None, max_length=100,null=True, blank=True )
    creacion = models.DateTimeField(auto_now_add=True)
    modificacion = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = "Articulo"
        verbose_name_plural = "Articulos"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.titulo)  # Genera el slug automáticamente
        super().save(*args, **kwargs)

class Imagen(models.Model):
    imagen = models.ImageField(
        upload_to='articulos/%Y/%m/%d/'
        )
    descripcion = models.CharField(max_length=255, blank=True)
    creado = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-creado']

    def __str__(self):
        return f"{self.imagen} - {self.descripcion}"


class ProveedorPublicidad(models.Model):
    nombre = models.CharField(max_length=255, unique=True)
    codigo_base = models.TextField(blank=True)

    def get_banner_ad(self):
        return self.formatopublicidad_set.filter(tipo='BANNER').first()

    def __str__(self):
        return self.nombre

class FormatoPublicidad(models.Model):
    TIPOS_FORMATO = [
        ('POPUNDER', 'Popunder'),
        ('BANNER', 'Banner'),
        ('NATIVO', 'Nativo'),
        ('SOCIAL', 'Barra Social'),
        ('VIDEO', 'Video'),
    ]
    proveedor_publicidad = models.ForeignKey(ProveedorPublicidad, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=20, choices=TIPOS_FORMATO)
    codigo = models.TextField()

    def __str__(self):
        return self.proveedor_publicidad.nombre


class ContenidoFragmento(models.Model):
    
    articulo = models.ForeignKey(Articulo, on_delete=models.CASCADE, related_name='fragmentos')
    orden = models.PositiveIntegerField(default=0)
    texto = models.TextField(blank=True, null=True)
    proveedor_publicidad = models.ForeignKey(ProveedorPublicidad, on_delete=models.CASCADE, null=True, blank=True)

    imagen = models.ForeignKey(
        Imagen,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ['orden']


    def __str__(self):
        return f"Fragmento {self.orden} - {self.articulo}"



class SideAd(models.Model):
    POSITION_CHOICES = [
        ('left', 'Izquierda'),
        ('right', 'Derecha'),
    ]
    
    articulo = models.ForeignKey(Articulo, on_delete=models.CASCADE, related_name='side_ads')
    position = models.CharField(max_length=10, choices=POSITION_CHOICES)
    proveedor_publicidad = models.ForeignKey(ProveedorPublicidad, on_delete=models.CASCADE)
    orden = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['orden']
        verbose_name = "Publicidad Lateral"
        verbose_name_plural = "Publicidades Laterales"

    def __str__(self):
        return f"{self.get_position_display()} - {self.proveedor_publicidad}"

apps/blog/views.py
from django.shortcuts import render
from django.utils import timezone
from rest_framework import generics
from .models import Articulo
from .serializers import ArticuloSerializer
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.http import Http404

from django.shortcuts import get_object_or_404

from .models import Articulo


# Create your views here.
class ArticuloView(ListView):
    model = Articulo
    paginate_by = 15  # if pagination is desired

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["lista-articulos"] = timezone.now()
        return context
    
class ArticuloDetailView(DetailView):
    model = Articulo
    slug_field = 'slug'  # Campo del modelo que contiene el slug
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["detail"] = timezone.now()
        return context




def trigger_404(request):
    raise Http404("Esta es una prueba de error 404")


#  - - - - api - - - - 



class ArticuloListAPIView(generics.ListAPIView):
    queryset = Articulo.objects.all()
    serializer_class = ArticuloSerializer

templates/blog/articulo_detail.html
{% extends "base/base.html" %}
{% load static %}
{% load i18n %}



{% block css %}               
<link rel="stylesheet" href="{% static 'css/base/base.css' %}?v={% now 'U' %}">
<link rel="stylesheet" href="{% static 'css/articulo_detail/articulo_detail_css.css' %}?v={% now 'U' %}">

{% endblock %}

{% block contenido %}
<main class="container">
    <aside class="sidebar sidebar-left ">
        <h2>Publicidad</h2>
        {% for ad in articulo.side_ads.all|dictsort:"orden" %}
        {% if ad.position == 'left' %}
          <div class="ad-banner ad-banner-vertical">
            {% with formato=ad.proveedor_publicidad.get_banner_ad %}
              {% if formato %}
              {% if fragmento.proveedor_publicidad %}
              <div class="ad-banner ad-banner-horizontal my-5 p-4">
                  {% with codigo=fragmento.proveedor_publicidad.formatopublicidad_set.first %}
                      {% if codigo %}
                          <div class="ad-code">
                              {{ codigo.codigo|safe }}
                          </div>
                      {% else %}
                          <p class="text-danger">Código de publicidad no configurado</p>
                      {% endif %}
                  {% endwith %}
              </div>
          {% endif %}
                <h3 class="ad-title">{{ ad.titulo }}</h3>
                <div class="ad-content">
                  {{ formato.codigo|safe }}
                </div>
                <span class="ad-cta">Descubre Más</span>
              {% else %}
                <p>Publicidad no disponible</p>
              {% endif %}
            {% endwith %}
          </div>
        {% endif %}
      {% endfor %}
    </aside>

    <section class="single-post-content">
        <h2>{{ object.title }}</h2>
        <p class="post-meta">Publicado el {{ articulo.creacion|date:"d F Y" }} por Admin</p>
        
        {% if articulo.image %}
        <div class="featured-image">
            <img src="{{ articulo.image.url }}" alt="{{ object.title }}" class="img-fluid">
        </div>
        {% endif %}
    
        <div class="text-content"> <!-- Envuelve todo el contenido textual -->
            <p class="lead">{{ object.descripcion }}</p>
    
            {% for fragmento in articulo.fragmentos.all|dictsort:"orden" %}
                {% if fragmento.texto %}
                    {{ fragmento.texto|linebreaks }}
                {% endif %}
    
              
                {% if fragmento.imagen %}
                <figure class="image-block">
                    <img src="{{ fragmento.imagen.imagen.url }}" class="img-fluid rounded"
                        alt="{{ fragmento.imagen.descripcion|default:'Imagen del artículo' }}" loading="lazy"
                        width=100%>
                    {% if fragmento.imagen.descripcion %}
                    <figcaption>{{ fragmento.imagen.descripcion }}</figcaption>
                    {% endif %}
                </figure>
                {% endif %}

                {% if fragmento.proveedor_publicidad %}
                <div class="ad-banner ad-banner-horizontal my-5 p-4">
                    {% with codigo=fragmento.proveedor_publicidad.formatopublicidad_set.first %}
                        {% if codigo %}
                            <div class="ad-code">
                                {{ codigo.codigo|safe }}
                            </div>
                        {% else %}
                            <p class="text-danger">Código de publicidad no configurado</p>
                        {% endif %}
                    {% endwith %}
                </div>
            {% endif %}
            {% endfor %}

            <footer class="article-footer">
                {% if articulo.modificacion %}
                <div class="update-info">
                    Actualizado: {{ articulo.modificacion|date:"d F Y H:i" }}
                </div>
                {% endif %}
                <a href="{% url 'blog:lista-articulos' %}" class="back-button">
                    &larr; Volver al blog
                </a>
            </footer>
        </div>
    
        <a href="{% url 'blog:lista-articulos' %}" class="back-link">&laquo; Volver al Blog</a>
    </section>

    <aside class="sidebar sidebar-right">
        <h2>Publicidad</h2>
        {% for ad in articulo.side_ads.all|dictsort:"orden" %}
        {% if ad.position == 'right' %}
        <div class="ad-banner ad-banner-square">
            {% with formato=ad.proveedor_publicidad.get_banner_ad %}
            {% if formato %}
            <p> {{ formato.codigo|safe }}
            </p>
            <span>Descubre Más</span>
            {% endif %}
            {% endwith %}
    
        </div>
    
    
    
        {% endif %}
        {% endfor %}
    
    </aside>
</main>
{% endblock %}

<script src="{% static 'js/base/base.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

templates/blog/articulo_list.html
{% extends "base/base.html" %}
{% load static %}  
{% load i18n %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/articulo_list_css/articulo_list_css.css' %}?v={% now 'U' %}">
<link rel="stylesheet" href="{% static 'css/base/base.css' %}?v={% now 'U' %}">

{% endblock %}

<head><base href="/" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>H4ckerPro - Blog</title>

    </head>
    
        {% block contenido %}
                
        <div class="blog-container dark-theme">
            <header class="blog-header">
              <h1>Blog de Ciberseguridad</h1>
              <p>Últimas noticias y artículos sobre seguridad informática</p>
            </header>
        
            <main class="blog-grid">
                {% for articulo in object_list %}
                    
                <article class="blog-card" > <!-- onclick="window.location.href='article.html?id=1'" -->
                    <a href="{% url 'blog:detalle-articulo' articulo.slug %}"><h2>{{ articulo.title }}</h2></a>
                    <div class="blog-meta">
                        <span>Por: Admin</span>
                  <span>{{ articulo.creacion }}/span>
                </div>
                <div class="blog-content">
                    <p>{{articulo.descripcion}}</p>
                </div>
                <div class="blog-footer">
                     <!-- 
                  <button class="like-button">
                        <svg viewBox="0 0 24 24" fill="currentColor">
                            <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/>
                        </svg>
                 
                    <span  class="likes-count">42</span>     
                  </button>
                  <div class="tags">
                    <span class="tag">Ransomware</span>
                    <span class="tag">Seguridad</span>
                  </div>  
                -->
                </div>
            </article>
            {% endfor %}
        

            </main>
          </div>

    
        {% endblock %}

      {% block add_scripst %}
        <script src="{% static 'js/articulo_list/articulo_list_js.js' %}"></script>
      {% endblock %}
    
    </html>

templates/blog/contacto.html
{% extends "blog/base.html" %}

{% block contenido %}
    
<main class="container">


    <section id="contacto" class="contact-section">
        <div class="container">
            <h2>Contacto</h2>
            <p>¿Tienes alguna pregunta o sugerencia? ¡Contáctanos!</p>
            <form id="contact-form">
                <div class="form-group">
                    <label for="name">Nombre:</label>
                    <input type="text" id="name" name="name" required>
                </div>
                <div class="form-group">
                    <label for="email">Correo Electrónico:</label>
                    <input type="email" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="message">Mensaje:</label>
                    <textarea id="message" name="message" rows="5" required></textarea>
                </div>
                <button type="submit" class="submit-button">Enviar Mensaje</button>
            </form>
        </div>
    </section>

</main>


{% endblock %}

<!-- Scripts adicionales para publicidad -->
<script>
    // Recargar los scripts de publicidad dinámicos
    document.addEventListener('DOMContentLoaded', function() {
        const ads = document.querySelectorAll('.ad-code script');
        ads.forEach(script => {
            const newScript = document.createElement('script');
            newScript.text = script.text;
            script.parentNode.replaceChild(newScript, script);
        });
    });
</script>


<!--

            <div class="ad-banner ad-banner-horizontal">
                <p>¡Anuncio Horizontal dentro del post!</p>
                <span>¡Oferta Exclusiva!</span>
            </div>

-->