apps/blog/urls.py
from django.urls import path
from . import views
from .views import ArticuloView, ArticuloDetailView, ArticuloListAPIView

app_name = 'blog'

urlpatterns = [
    path("blog", ArticuloView.as_view(), name="lista-articulos"),
    path("detail/<slug:slug>/", ArticuloDetailView.as_view(), name="detalle-articulo"),
    path('test-404/', views.trigger_404),
    path('api/articulos/', ArticuloListAPIView.as_view(), name='articulo-list'),

]

apps/home/urls.py
from django.urls import path


from .views import HomeView

app_name = "home_app"


urlpatterns = [
    path('', HomeView.as_view(), name='home-view')

]

apps/users/urls.py
from django.urls import path
from .views import CustomTokenObtainPairView, LogoutView
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (UserRegisterView,
                    LogoutView,
                    LoginUser,
                    CodeVerificationView,
                        # vistas para el reseteo del password
                    CustomPasswordResetView,
                    CustomPasswordResetDoneView,
                    CustomPasswordResetConfirmView,
                    CustomPasswordResetCompleteView,
                    logout_view
                    )

app_name = "users_app"


urlpatterns = [
    path('api/token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/logout/', LogoutView.as_view(), name='token_revocado'),
    # rutas normales sin la api
   path('register/', UserRegisterView.as_view(), name='user-register',),
    path(
        'login/', 
        LoginUser.as_view(),
        name='user-login',
    ),
       path(
        'user-verification/<int:pk>/', 
        CodeVerificationView.as_view(),
        name='user-verification',
    ),
    path('logout/', logout_view, name='logout'),
    # rutas usadas para el cambio de la contraseña
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

cyberblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('blog/', include('apps.blog.urls')),
    path('landing/', TemplateView.as_view(template_name='base/base.html'), name='landing'),  # Página de inicio
    path('users/', include('apps.users.urls')),
    path('', include('apps.home.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/componentes/navbar/navbar.html
<div class="nav-container ">
  <nav class="navbar">
    <a href="https://h4ckerpro.com" class="logo">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" />
      </svg>
      CyberBlog
    </a>

    <ul class="nav-links">
      <li><a href="{% url 'home_app:home-view' %}">Inicio</a></li>
      <li><a href="{% url 'blog:lista-articulos' %}">Blog</a></li>

      {% if user.is_authenticated %}
      <li>
        <a href="{% url 'users_app:logout' %}">Cerrar sesión</a>
      </li>
      {% else %}
      <li><a href="{% url 'users_app:user-login' %}">Login</a></li>
      <li><a href="{% url 'users_app:user-register' %}">register</a></li>

      {% endif %}
      
    </ul>

    <button class="theme-toggle" id="themeToggle">
      <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor" class="theme-icon">
        <path class="sun-icon"
          d="M12 1v2m0 18v2M4.22 4.22l1.42 1.42m12.72 12.72l1.42 1.42M1 12h2m18 0h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42M12 6a6 6 0 100 12 6 6 0 000-12z" />
        <path class="moon-icon" style="display:none" d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z" />
      </svg>
      <span class="theme-text">Tema</span>
    </button>

    <button class="hamburger" id="hamburger">
      ☰
    </button>
  </nav>
</div>